<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="set" nsURI="" nsPrefix="htwg.mgse">
  <eSubpackages name="modell">
    <eClassifiers xsi:type="ecore:EClass" name="ICard" abstract="true" interface="true">
      <eOperations name="getColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getForm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getPanelFilling" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getNumberOfComponents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ACard" abstract="true" eSuperTypes="#//modell/ICard"/>
    <eClassifiers xsi:type="ecore:EClass" name="IField" abstract="true" interface="true">
      <eOperations name="startUp"/>
      <eOperations name="getCardsInField">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments/>
        </eGenericType>
      </eOperations>
      <eOperations name="foundSet">
        <eParameters name="cardOne" eType="#//modell/ICard"/>
        <eParameters name="cardTwo" eType="#//modell/ICard"/>
        <eParameters name="cardThree" eType="#//modell/ICard"/>
      </eOperations>
      <eOperations name="changeCards">
        <eParameters name="list">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
            <eTypeArguments/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="getUnusedCards">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments/>
        </eGenericType>
      </eOperations>
      <eOperations name="getSizeofField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getAllCardsInGame">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments/>
        </eGenericType>
      </eOperations>
      <eOperations name="getCardInFieldGame" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMap"/>
      <eOperations name="clear"/>
      <eOperations name="setSizeOfField">
        <eParameters name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AFIeld" abstract="true" eSuperTypes="#//modell/IField"/>
  </eSubpackages>
  <eSubpackages name="controller">
    <eClassifiers xsi:type="ecore:EClass" name="IController" eSuperTypes="#//util/observer/IObservable">
      <eOperations name="isAsetForController">
        <eParameters name="cardOne" eType="#//modell/ICard"/>
        <eParameters name="cardTwo" eType="#//modell/ICard"/>
        <eParameters name="cardThree" eType="#//modell/ICard"/>
      </eOperations>
      <eOperations name="getCardinGame">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getField" eType="#//impl/Field"/>
      <eOperations name="areSetInField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getAsetInGame">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eOperations>
      <eOperations name="stillSetInGAme" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getSetInField">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eOperations>
      <eOperations name="geTplayerOnePoints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="geTplayerTwoPoints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getPlayerOne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getPlayerTwo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="newGame"/>
      <eOperations name="setFieldSize">
        <eParameters name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getCardInFieldGame">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getCardsAndTheIndexOfCardInField">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="impl" nsPrefix="model">
    <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//modell/AFIeld">
      <eOperations name="startUp"/>
      <eOperations name="rand">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eGenericType>
      </eOperations>
      <eOperations name="foundSet">
        <eParameters name="cardOne" eType="#//modell/ICard"/>
        <eParameters name="cardTwo" eType="#//modell/ICard"/>
        <eParameters name="cardThree" eType="#//modell/ICard"/>
      </eOperations>
      <eOperations name="fillField"/>
      <eOperations name="getCardsInField">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eOperations>
      <eOperations name="setSizeOfField">
        <eParameters name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="changeCards">
        <eParameters name="liste">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
            <eTypeArguments eClassifier="#//modell/ICard"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="getUnusedCards">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getSizeofField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getAllCardsInGame">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getRandomListe">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getCardInFieldGame">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eOperations>
      <eOperations name="clear"/>
      <eOperations name="toString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="returnApeend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="returnString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="apendKeyInString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="appendColorInString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="appendFormInString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="appendNumberOfComponents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="appendFillingInString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeOfField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="INITIALVALUEOFFIELD"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
          defaultValueLiteral="12"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          changeable="false" defaultValueLiteral="81"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ONE" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="NUMBERFORONELINE" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="LEGHTFORSTRING" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="listeofcontains">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ramdomListe">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardInFieldGame">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packForGame">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Card" eSuperTypes="#//modell/ACard">
      <eOperations name="compareTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="card" eType="#//modell/ACard"/>
      </eOperations>
      <eOperations name="new" eType="#//impl/Card">
        <eParameters name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="form" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="panelFilling" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="anz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="form" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="panelFilling" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pack" eSuperTypes="#//modell/ICard">
      <eOperations name="Pack"/>
      <eOperations name="createCards">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//impl/Card"/>
        </eGenericType>
      </eOperations>
      <eOperations name="setFormedIndex"/>
      <eOperations name="setFillIndex"/>
      <eOperations name="setComponentsOfIndex"/>
      <eOperations name="setColorIndex"/>
      <eOperations name="getPack">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//modell/ICard"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getcolors">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getFormes">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getFill">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="FORME">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="COLORS">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="FILL">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="NUMBEROFCOMPONET">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SIZEOFARRAY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="NUMBEROFEACHCARD" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="colorIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="formeIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillgingIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numbersIdex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="util">
    <eSubpackages name="observer">
      <eClassifiers xsi:type="ecore:EClass" name="Event"/>
      <eClassifiers xsi:type="ecore:EClass" name="IObservable">
        <eOperations name="addObserver">
          <eParameters name="s" eType="#//util/observer/IObservable"/>
        </eOperations>
        <eOperations name="removeObserver">
          <eParameters name="s" eType="#//util/observer/IObservable"/>
        </eOperations>
        <eOperations name="removeAllObservers"/>
        <eOperations name="notifyObservers"/>
        <eOperations name="notifyObservers">
          <eParameters name="e" eType="#//util/observer/Event"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IObserver">
        <eOperations name="update">
          <eParameters name="e" eType="#//util/observer/Event"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Observable" eSuperTypes="#//util/observer/IObservable">
        <eOperations name="addObserver">
          <eParameters name="s" eType="#//util/observer/IObservable"/>
        </eOperations>
        <eOperations name="removeObserver">
          <eParameters name="s" eType="#//util/observer/IObservable"/>
        </eOperations>
        <eOperations name="removeAllObservers"/>
        <eOperations name="notifyObservers"/>
        <eOperations name="notifyObservers">
          <eParameters name="e" eType="#//util/observer/Event"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="subscribers">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
            <eTypeArguments eClassifier="#//util/observer/IObserver"/>
          </eGenericType>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
