/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ide;

import org.xtext.de.htwg.ide.AbstractSetIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SetIdeModule extends AbstractSetIdeModule {
}
