/*
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractSetScopeProvider extends XbaseBatchScopeProvider {
}
