/**
 * generated by Xtext 2.11.0
 */
package org.xtext.mgse.validation;

import org.xtext.mgse.validation.AbstractSetValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SetValidator extends AbstractSetValidator {
}
