/*
 * generated by Xtext 2.11.0
 */
package org.xtext.mgse


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SetStandaloneSetup extends SetStandaloneSetupGenerated {

	def static void doSetup() {
		new SetStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
