/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.set;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PACK</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.de.htwg.set.PACK#getPack <em>Pack</em>}</li>
 * </ul>
 *
 * @see org.xtext.de.htwg.set.SetPackage#getPACK()
 * @model
 * @generated
 */
public interface PACK extends EObject
{
  /**
   * Returns the value of the '<em><b>Pack</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pack</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pack</em>' containment reference.
   * @see #setPack(PACKTYPE)
   * @see org.xtext.de.htwg.set.SetPackage#getPACK_Pack()
   * @model containment="true"
   * @generated
   */
  PACKTYPE getPack();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.set.PACK#getPack <em>Pack</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pack</em>' containment reference.
   * @see #getPack()
   * @generated
   */
  void setPack(PACKTYPE value);

} // PACK
