/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.set;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PACKTYPE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.de.htwg.set.PACKTYPE#getForms <em>Forms</em>}</li>
 *   <li>{@link org.xtext.de.htwg.set.PACKTYPE#getUrl <em>Url</em>}</li>
 * </ul>
 *
 * @see org.xtext.de.htwg.set.SetPackage#getPACKTYPE()
 * @model
 * @generated
 */
public interface PACKTYPE extends EObject
{
  /**
   * Returns the value of the '<em><b>Forms</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Forms</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forms</em>' attribute.
   * @see #setForms(String)
   * @see org.xtext.de.htwg.set.SetPackage#getPACKTYPE_Forms()
   * @model
   * @generated
   */
  String getForms();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.set.PACKTYPE#getForms <em>Forms</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Forms</em>' attribute.
   * @see #getForms()
   * @generated
   */
  void setForms(String value);

  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Url</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see org.xtext.de.htwg.set.SetPackage#getPACKTYPE_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link org.xtext.de.htwg.set.PACKTYPE#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

} // PACKTYPE
