/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.set;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.de.htwg.set.SetPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends Feature
{
} // Property
