/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.set;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.de.htwg.set.SetPackage
 * @generated
 */
public interface SetFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SetFactory eINSTANCE = org.xtext.de.htwg.set.impl.SetFactoryImpl.init();

  /**
   * Returns a new object of class '<em>PACK</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PACK</em>'.
   * @generated
   */
  PACK createPACK();

  /**
   * Returns a new object of class '<em>PACKTYPE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PACKTYPE</em>'.
   * @generated
   */
  PACKTYPE createPACKTYPE();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SetPackage getSetPackage();

} //SetFactory
