/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.set;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.de.htwg.set.SetFactory
 * @model kind="package"
 * @generated
 */
public interface SetPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "set";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/de/htwg/Set";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "set";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SetPackage eINSTANCE = org.xtext.de.htwg.set.impl.SetPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.de.htwg.set.impl.PACKImpl <em>PACK</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.de.htwg.set.impl.PACKImpl
   * @see org.xtext.de.htwg.set.impl.SetPackageImpl#getPACK()
   * @generated
   */
  int PACK = 0;

  /**
   * The feature id for the '<em><b>Pack</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACK__PACK = 0;

  /**
   * The number of structural features of the '<em>PACK</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.de.htwg.set.impl.PACKTYPEImpl <em>PACKTYPE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.de.htwg.set.impl.PACKTYPEImpl
   * @see org.xtext.de.htwg.set.impl.SetPackageImpl#getPACKTYPE()
   * @generated
   */
  int PACKTYPE = 1;

  /**
   * The feature id for the '<em><b>Forms</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKTYPE__FORMS = 0;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKTYPE__URL = 1;

  /**
   * The number of structural features of the '<em>PACKTYPE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKTYPE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.de.htwg.set.PACK <em>PACK</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PACK</em>'.
   * @see org.xtext.de.htwg.set.PACK
   * @generated
   */
  EClass getPACK();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.de.htwg.set.PACK#getPack <em>Pack</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pack</em>'.
   * @see org.xtext.de.htwg.set.PACK#getPack()
   * @see #getPACK()
   * @generated
   */
  EReference getPACK_Pack();

  /**
   * Returns the meta object for class '{@link org.xtext.de.htwg.set.PACKTYPE <em>PACKTYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PACKTYPE</em>'.
   * @see org.xtext.de.htwg.set.PACKTYPE
   * @generated
   */
  EClass getPACKTYPE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.de.htwg.set.PACKTYPE#getForms <em>Forms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Forms</em>'.
   * @see org.xtext.de.htwg.set.PACKTYPE#getForms()
   * @see #getPACKTYPE()
   * @generated
   */
  EAttribute getPACKTYPE_Forms();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.de.htwg.set.PACKTYPE#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.de.htwg.set.PACKTYPE#getUrl()
   * @see #getPACKTYPE()
   * @generated
   */
  EAttribute getPACKTYPE_Url();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SetFactory getSetFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.de.htwg.set.impl.PACKImpl <em>PACK</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.de.htwg.set.impl.PACKImpl
     * @see org.xtext.de.htwg.set.impl.SetPackageImpl#getPACK()
     * @generated
     */
    EClass PACK = eINSTANCE.getPACK();

    /**
     * The meta object literal for the '<em><b>Pack</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACK__PACK = eINSTANCE.getPACK_Pack();

    /**
     * The meta object literal for the '{@link org.xtext.de.htwg.set.impl.PACKTYPEImpl <em>PACKTYPE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.de.htwg.set.impl.PACKTYPEImpl
     * @see org.xtext.de.htwg.set.impl.SetPackageImpl#getPACKTYPE()
     * @generated
     */
    EClass PACKTYPE = eINSTANCE.getPACKTYPE();

    /**
     * The meta object literal for the '<em><b>Forms</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKTYPE__FORMS = eINSTANCE.getPACKTYPE_Forms();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKTYPE__URL = eINSTANCE.getPACKTYPE_Url();

  }

} //SetPackage
