/*
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.de.htwg.SetRuntimeModule
import org.xtext.de.htwg.SetStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SetIdeSetup extends SetStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SetRuntimeModule, new SetIdeModule))
	}
	
}
