/**
 * generated by Xtext 2.11.0
 */
package org.xtext.de.htwg.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.de.htwg.tests.SetInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(SetInjectorProvider.class)
@SuppressWarnings("all")
public class SetParsingTest {
  @Inject
  private /* ParseHelper<Domainmodel> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SetParsingTest.parseHelper refers to the missing type Domainmodel"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
