/*
 * generated by Xtext 2.11.0
 */
package org.xtext.mgse.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.mgse.set.ui.internal.SetActivator;

public class SetUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SetActivator.getInstance().getInjector("org.xtext.mgse.Set");
	}

}
