/**
 * generated by Xtext 2.11.0
 */
package org.xtext.mgse.set;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FORMS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mgse.set.FORMS#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mgse.set.FORMS#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.mgse.set.SetPackage#getFORMS()
 * @model
 * @generated
 */
public interface FORMS extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mgse.set.SetPackage#getFORMS_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mgse.set.FORMS#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.mgse.set.TYPE_FORMS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.mgse.set.TYPE_FORMS
   * @see #setType(TYPE_FORMS)
   * @see org.xtext.mgse.set.SetPackage#getFORMS_Type()
   * @model
   * @generated
   */
  TYPE_FORMS getType();

  /**
   * Sets the value of the '{@link org.xtext.mgse.set.FORMS#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.mgse.set.TYPE_FORMS
   * @see #getType()
   * @generated
   */
  void setType(TYPE_FORMS value);

} // FORMS
