/**
 * generated by Xtext 2.11.0
 */
package org.xtext.mgse.set;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>TYPE FORMS</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.mgse.set.SetPackage#getTYPE_FORMS()
 * @model
 * @generated
 */
public enum TYPE_FORMS implements Enumerator
{
  /**
   * The '<em><b>FORM ORIGINAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORM_ORIGINAL_VALUE
   * @generated
   * @ordered
   */
  FORM_ORIGINAL(0, "FORM_ORIGINAL", "FORM_ORIGINAL"),

  /**
   * The '<em><b>FORM DOCTORWHO</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORM_DOCTORWHO_VALUE
   * @generated
   * @ordered
   */
  FORM_DOCTORWHO(1, "FORM_DOCTORWHO", "FORM_DOCTORWHO"),

  /**
   * The '<em><b>FORM GAMEOFTHRONES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORM_GAMEOFTHRONES_VALUE
   * @generated
   * @ordered
   */
  FORM_GAMEOFTHRONES(2, "FORM_GAMEOFTHRONES", "FORM_GAMEOFTHRONES");

  /**
   * The '<em><b>FORM ORIGINAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FORM ORIGINAL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FORM_ORIGINAL
   * @model
   * @generated
   * @ordered
   */
  public static final int FORM_ORIGINAL_VALUE = 0;

  /**
   * The '<em><b>FORM DOCTORWHO</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FORM DOCTORWHO</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FORM_DOCTORWHO
   * @model
   * @generated
   * @ordered
   */
  public static final int FORM_DOCTORWHO_VALUE = 1;

  /**
   * The '<em><b>FORM GAMEOFTHRONES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FORM GAMEOFTHRONES</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FORM_GAMEOFTHRONES
   * @model
   * @generated
   * @ordered
   */
  public static final int FORM_GAMEOFTHRONES_VALUE = 2;

  /**
   * An array of all the '<em><b>TYPE FORMS</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final TYPE_FORMS[] VALUES_ARRAY =
    new TYPE_FORMS[]
    {
      FORM_ORIGINAL,
      FORM_DOCTORWHO,
      FORM_GAMEOFTHRONES,
    };

  /**
   * A public read-only list of all the '<em><b>TYPE FORMS</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<TYPE_FORMS> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>TYPE FORMS</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TYPE_FORMS get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TYPE_FORMS result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>TYPE FORMS</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TYPE_FORMS getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TYPE_FORMS result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>TYPE FORMS</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TYPE_FORMS get(int value)
  {
    switch (value)
    {
      case FORM_ORIGINAL_VALUE: return FORM_ORIGINAL;
      case FORM_DOCTORWHO_VALUE: return FORM_DOCTORWHO;
      case FORM_GAMEOFTHRONES_VALUE: return FORM_GAMEOFTHRONES;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private TYPE_FORMS(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //TYPE_FORMS
