/**
 * generated by Xtext 2.11.0
 */
package org.xtext.mgse.set;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>URL TYPES</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.mgse.set.SetPackage#getURL_TYPES()
 * @model
 * @generated
 */
public enum URL_TYPES implements Enumerator
{
  /**
   * The '<em><b>URL ORIGINAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #URL_ORIGINAL_VALUE
   * @generated
   * @ordered
   */
  URL_ORIGINAL(0, "URL_ORIGINAL", "URL_ORIGINAL"),

  /**
   * The '<em><b>URL DOCTORWHO</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #URL_DOCTORWHO_VALUE
   * @generated
   * @ordered
   */
  URL_DOCTORWHO(1, "URL_DOCTORWHO", "URL_DOCTORWHO"),

  /**
   * The '<em><b>URL GAMEOFTHRONES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #URL_GAMEOFTHRONES_VALUE
   * @generated
   * @ordered
   */
  URL_GAMEOFTHRONES(2, "URL_GAMEOFTHRONES", "URL_GAMEOFTHRONES");

  /**
   * The '<em><b>URL ORIGINAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>URL ORIGINAL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #URL_ORIGINAL
   * @model
   * @generated
   * @ordered
   */
  public static final int URL_ORIGINAL_VALUE = 0;

  /**
   * The '<em><b>URL DOCTORWHO</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>URL DOCTORWHO</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #URL_DOCTORWHO
   * @model
   * @generated
   * @ordered
   */
  public static final int URL_DOCTORWHO_VALUE = 1;

  /**
   * The '<em><b>URL GAMEOFTHRONES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>URL GAMEOFTHRONES</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #URL_GAMEOFTHRONES
   * @model
   * @generated
   * @ordered
   */
  public static final int URL_GAMEOFTHRONES_VALUE = 2;

  /**
   * An array of all the '<em><b>URL TYPES</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final URL_TYPES[] VALUES_ARRAY =
    new URL_TYPES[]
    {
      URL_ORIGINAL,
      URL_DOCTORWHO,
      URL_GAMEOFTHRONES,
    };

  /**
   * A public read-only list of all the '<em><b>URL TYPES</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<URL_TYPES> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>URL TYPES</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static URL_TYPES get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      URL_TYPES result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>URL TYPES</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static URL_TYPES getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      URL_TYPES result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>URL TYPES</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static URL_TYPES get(int value)
  {
    switch (value)
    {
      case URL_ORIGINAL_VALUE: return URL_ORIGINAL;
      case URL_DOCTORWHO_VALUE: return URL_DOCTORWHO;
      case URL_GAMEOFTHRONES_VALUE: return URL_GAMEOFTHRONES;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private URL_TYPES(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //URL_TYPES
