/**
 * generated by Xtext 2.11.0
 */
package org.xtext.mgse.set.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.mgse.set.SetFactory;
import org.xtext.mgse.set.SetPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SetPackageImpl extends EPackageImpl implements SetPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass packEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass packtypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass formsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass urlEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum typE_FORMSEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum urL_TYPESEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.mgse.set.SetPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private SetPackageImpl()
  {
    super(eNS_URI, SetFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link SetPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static SetPackage init()
  {
    if (isInited) return (SetPackage)EPackage.Registry.INSTANCE.getEPackage(SetPackage.eNS_URI);

    // Obtain or create and register package
    SetPackageImpl theSetPackage = (SetPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof SetPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new SetPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theSetPackage.createPackageContents();

    // Initialize created meta-data
    theSetPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theSetPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(SetPackage.eNS_URI, theSetPackage);
    return theSetPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPACK()
  {
    return packEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPACK_Name()
  {
    return (EAttribute)packEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPACK_Type()
  {
    return (EReference)packEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPACKTYPE()
  {
    return packtypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPACKTYPE_Forms()
  {
    return (EReference)packtypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPACKTYPE_Url()
  {
    return (EReference)packtypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFORMS()
  {
    return formsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFORMS_Name()
  {
    return (EAttribute)formsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFORMS_Type()
  {
    return (EAttribute)formsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getURL()
  {
    return urlEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getURL_Name()
  {
    return (EAttribute)urlEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getURL_Type()
  {
    return (EAttribute)urlEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getTYPE_FORMS()
  {
    return typE_FORMSEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getURL_TYPES()
  {
    return urL_TYPESEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SetFactory getSetFactory()
  {
    return (SetFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    packEClass = createEClass(PACK);
    createEAttribute(packEClass, PACK__NAME);
    createEReference(packEClass, PACK__TYPE);

    packtypeEClass = createEClass(PACKTYPE);
    createEReference(packtypeEClass, PACKTYPE__FORMS);
    createEReference(packtypeEClass, PACKTYPE__URL);

    formsEClass = createEClass(FORMS);
    createEAttribute(formsEClass, FORMS__NAME);
    createEAttribute(formsEClass, FORMS__TYPE);

    urlEClass = createEClass(URL);
    createEAttribute(urlEClass, URL__NAME);
    createEAttribute(urlEClass, URL__TYPE);

    // Create enums
    typE_FORMSEEnum = createEEnum(TYPE_FORMS);
    urL_TYPESEEnum = createEEnum(URL_TYPES);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(packEClass, org.xtext.mgse.set.PACK.class, "PACK", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPACK_Name(), ecorePackage.getEString(), "name", null, 0, 1, org.xtext.mgse.set.PACK.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPACK_Type(), this.getPACKTYPE(), null, "type", null, 0, 1, org.xtext.mgse.set.PACK.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(packtypeEClass, org.xtext.mgse.set.PACKTYPE.class, "PACKTYPE", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPACKTYPE_Forms(), this.getFORMS(), null, "forms", null, 0, 1, org.xtext.mgse.set.PACKTYPE.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPACKTYPE_Url(), this.getURL(), null, "url", null, 0, 1, org.xtext.mgse.set.PACKTYPE.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(formsEClass, org.xtext.mgse.set.FORMS.class, "FORMS", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFORMS_Name(), ecorePackage.getEString(), "name", null, 0, 1, org.xtext.mgse.set.FORMS.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFORMS_Type(), this.getTYPE_FORMS(), "type", null, 0, 1, org.xtext.mgse.set.FORMS.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(urlEClass, org.xtext.mgse.set.URL.class, "URL", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getURL_Name(), ecorePackage.getEString(), "name", null, 0, 1, org.xtext.mgse.set.URL.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getURL_Type(), this.getURL_TYPES(), "type", null, 0, 1, org.xtext.mgse.set.URL.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(typE_FORMSEEnum, org.xtext.mgse.set.TYPE_FORMS.class, "TYPE_FORMS");
    addEEnumLiteral(typE_FORMSEEnum, org.xtext.mgse.set.TYPE_FORMS.FORM_ORIGINAL);
    addEEnumLiteral(typE_FORMSEEnum, org.xtext.mgse.set.TYPE_FORMS.FORM_DOCTORWHO);
    addEEnumLiteral(typE_FORMSEEnum, org.xtext.mgse.set.TYPE_FORMS.FORM_GAMEOFTHRONES);

    initEEnum(urL_TYPESEEnum, org.xtext.mgse.set.URL_TYPES.class, "URL_TYPES");
    addEEnumLiteral(urL_TYPESEEnum, org.xtext.mgse.set.URL_TYPES.URL_ORIGINAL);
    addEEnumLiteral(urL_TYPESEEnum, org.xtext.mgse.set.URL_TYPES.URL_DOCTORWHO);
    addEEnumLiteral(urL_TYPESEEnum, org.xtext.mgse.set.URL_TYPES.URL_GAMEOFTHRONES);

    // Create resource
    createResource(eNS_URI);
  }

} //SetPackageImpl
