/**
 * generated by Xtext 2.11.0
 */
package org.xtext.mgse.ui.contentassist;

import org.xtext.mgse.ui.contentassist.AbstractSetProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SetProposalProvider extends AbstractSetProposalProvider {
}
